# These are supported funding model platforms

# github: potatoqualitee, wsmelton # we're not sponsorable yet :( beta's taking so long
patreon: potatoqualitee
open_collective: dbatools
custom: paypal.me/potatoqualitee
